name: Upload data to website

on:
  schedule:
    - cron: '0 15 * * 1-5'
  workflow_dispatch:

jobs:
  upload-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          ls -la
          python -m src.pipeline
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          IS_PROD: ${{ secrets.IS_PROD }}

      - name: Clone website
        run: |
          git clone https://${{ secrets.REPO_TOKEN }}@github.com/can-be-anything/website.git website-repo

      - name: Copy file to website
        run: |
          ls -la
          cp -Rf prod-database/ website-repo/website/src/data

      - name: Commit and Push 
        run: |
          git config --global user.email "auto@robot.xyz"
          git config --global user.name "ci/cd"
          git add .
          git commit -m "update data"
          git push origin main
          cd website-repo
          git add .
          git commit -m "update data"
          git push origin main
